version: '2.3'

services:
  logstash:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: logstash
    hostname: logstash
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/jvm.options:/usr/share/logstash/config/jvm.options
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./config/pipelines:/usr/share/logstash/pipeline
      - ./config/files:/usr/files
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 10s
      retries: 10
    depends_on:
      - localstack
    ports:
      - 9600:9600
    expose:
      - 9600
    networks:
      - indexer

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - indexer

networks:
  indexer:
    driver: bridge
